# Generated by Django 3.2 on 2023-08-31 14:59

import django.core.validators
from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230824_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Недопустимые символы для имени пользователя', regex='^[\\w.@+-]+$'), users.validators.validate_username], verbose_name='Имя пользователя'),
        ),
    ]
